apiVersion: apps/v1
kind: Deployment
metadata:
  name: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: {{ .Values.common-template.image.repository  }}:{{ Values.common-template.image.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 80